g_messages = {}
g_messages["NNKA"] = "Script started."                                     -- Старт скрипта
g_messages["QZR4"] = "Script stoped."                                      -- Стоп скрипта
g_messages["YNNJ"] = "Monitoring table created."                           -- Создана таблица мониторинга
g_messages["V8BW"] = "Monitoring table deleted."                           -- Удаление таблица мониторинга
g_messages["2SOT"] = "Row added to monitoring table."                      -- Добавление столбца в таблицу
g_messages["D6K6"] = "Row updated in monitoring table."                    -- Обновление таблицы
g_messages["I93O"] = "No trading time."                                    -- Не торговое время
g_messages["2HB7"] = "Database is not available."                          -- База данных недоступна
g_messages["OL2F"] = "Quik server is not available."                       -- Сервер Quik недоступен
g_messages["2BYO"] = "Candles are not available."                          -- Свечи недоступны
g_messages["6LF3"] = "The number of candles is less than n"                -- Количество свечей меньше N
g_messages["MKHF"] = "FORTS account is not available."                     -- Счет ФОРТС недоступен
g_messages["WVEF"] = "Function BitIsTrue returns nil."                     -- Функция BitIsTrue вернула nil
g_messages["59X5"] = "Function getNumCandles returns nil."                 -- Функция getNumCandles вернула nil
g_messages["PCC5"] = "Function getNumberOf returns nil."                   -- Функция getNumberOf вернула nil
g_messages["31QI"] = "Function getNumberOf returns 0"                      -- Функция getNumberOf вернула 0
g_messages["37WS"] = "Function getItem returns nil."                       -- Функция getItem вернула nil
g_messages["OJJ2"] = "Function getCandlesByIndex returns nil."             -- Функция getCandlesByIndex вернула nil
g_messages["JC3M"] = "Function getCandlesByIndex returns 0."               -- Функция getCandlesByIndex вернула 0
g_messages["7EVT"] = "Function getCandlesByIndex returns incorrect value." -- Функция getCandlesByIndex вернула некорректное значение
g_messages["3XP2"] = "Variable is nil."                                    -- Переменная равна nil
g_messages["1V21"] = "Variable is 0."                                      -- Переменная равна 0
g_messages["3WFV"] = "Function argument is nil."                           -- Аргумент функции равен nil
g_messages["5C82"] = "Candle with index 0."                                -- Свеча с индексом 0
g_messages["1I9N"] = "Candle with index -1."                               -- Свеча с индексом -1
g_messages["JCC1"] = "Candle with index -2."                               -- Свеча с индексом -2
g_messages["9LDT"] = "Candle saved in DB."                                 -- Свеча сохранена в БД
g_messages["QL9Z"] = "Count rows in DB table."                             -- Количество строк в таблице БД   
g_messages["RWEB"] = "Account is nil."                                     -- Значение аккаунта
g_messages["OA7E"] = "Trader ID is nil."                                   -- Идентификатор трейдера не задан
g_messages["FQCD"] = "Class code is nil."                                  -- Класс инструмента не задан
g_messages["ZJON"] = "Security code is nil."                               -- Тикер инструмента не задан
g_messages["MN58"] = "Price is nil."                                       -- Цена не задана
g_messages["S3MV"] = "Quantity is nil."                                    -- Количество не задано
g_messages["GBC4"] = "Operation is nil."                                   -- Тип операции не задан
g_messages["R4OV"] = "Limit order sent to terminal."                       -- Лимитная заявка отправлена в терминал
g_messages["5KOS"] = "Limit order executed."                               -- Лимитная заявка исполнена
g_messages["1HGF"] = "Limit order not executed, remove the balance."       -- Заявка не исполнена, снимается остаток
g_messages["9VAO"] = "Limit order not executed in timeout."                -- Заявка не исполнена в течение тайм-аута
g_messages["D0XP"] = "Send buy order"  								       -- Докупка
g_messages["AIPM"] = "Send sell order" 									   -- Допродажа                                      
g_messages["SEPN"] = ""                                                 
g_messages["SC3L"] = ""                                                 
g_messages["XMI9"] = "" 
g_messages["ER80"] = "" 
g_messages["RKI0"] = "" 
g_messages["HG6J"] = "" 
g_messages["91VY"] = "" 
g_messages["XL6I"] = "" 
g_messages["OFR3"] = "" 
g_messages["O0VF"] = "" 
g_messages["VXNM"] = "" 
g_messages["86W1"] = "" 
g_messages["3MC0"] = "" 
g_messages["E1H6"] = "" 
g_messages["51UI"] = "" 
g_messages["99LQ"] = "" 
g_messages["DMXA"] = "" 
g_messages["TPJC"] = "" 
g_messages["PO7E"] = "" 
g_messages["292Y"] = "" 
g_messages["1ZB3"] = ""
g_messages["DBXP"] = ""
g_messages["N9XT"] = ""
g_messages["Q9J5"] = ""
g_messages["C7ED"] = ""
g_messages["V0LW"] = ""
g_messages["AGXO"] = ""
g_messages["C4JP"] = ""
g_messages["FLIW"] = ""
g_messages["VQBO"] = ""
g_messages["TJXC"] = ""
g_messages["TBZV"] = ""
g_messages["NPGD"] = ""
g_messages["R8L6"] = ""
g_messages["83VD"] = ""
g_messages["0B6Z"] = "" 
g_messages["SADX"] = "" 
g_messages["CP6V"] = "" 
g_messages["381Z"] = ""
g_messages["G63D"] = ""
g_messages["R50Z"] = ""
g_messages["JNEX"] = ""
g_messages["IE7X"] = ""
g_messages["E9GQ"] = ""
g_messages["9GGZ"] = ""
g_messages["SYX8"] = ""
g_messages["ZPM8"] = ""
g_messages["OG7R"] = ""
g_messages["AVJH"] = ""
g_messages["L7GD"] = ""
g_messages["TXPL"] = ""
g_messages["KCNX"] = ""
g_messages["EQQP"] = ""
g_messages["V21O"] = ""
g_messages["Z6OM"] = ""
g_messages["IYA3"] = ""
g_messages["C91R"] = ""
g_messages["28W0"] = ""
g_messages["V3E9"] = ""